version: "2"
services:
  web:
    build: .
    ports:
    - 8000:8000
    depends_on:
      - db
    restart: always

  db:
    build:
      context: "."
      dockerfile: "Dockerfile-postgres"
    environment:
      POSTGRES_PASSWORD: optrix
    hostname: "database"
    volumes:
      - /var/lib/postgresql/data
    restart: always