version: "3.3"
volumes:
  static_volume:
  media_volume:
services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - static_volume:/srv/deploy/optrix/htdocs
      - media_volume:/srv/deploy/optrix/media
    ports:
    - 8000:8000
    depends_on:
      - db
    user: root
    command: /srv/deploy/optrix/db/run_wsgi.sh
    restart: always

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/srv/deploy/optrix/htdocs
      - media_volume:/srv/deploy/optrix/media
    ports:
      - 80:80
    depends_on:
      - web
  db:
    build:
      context: "."
      dockerfile: "Dockerfile-postgres"
    env_file:
      - .env_db
    ports:
      - 5432:5432
    restart: always