# Generated by Django 3.0.3 on 2020-02-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date of surgery')),
                ('number', models.IntegerField(verbose_name='Patient number')),
                ('crypto_key', models.CharField(max_length=100, verbose_name='Patient key')),
                ('sex', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('diagnosis', models.CharField(max_length=16, verbose_name='Disease code (ICD-10)')),
                ('asa_grade', models.FloatField(verbose_name='ASA grade')),
            ],
        ),
    ]
