# Generated by Django 3.0.3 on 2020-02-13 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optrix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('surgery_type', models.CharField(max_length=256)),
                ('patient_in', models.TimeField(verbose_name='patient entered the operating room')),
                ('patient_out', models.TimeField(verbose_name='Patient left the operating room')),
                ('anesthetic_induction', models.CharField(max_length=512)),
                ('robotic', models.BooleanField(default=False)),
                ('incision_time', models.TimeField()),
                ('suture_time', models.TimeField()),
                ('estimated_blood_loss', models.FloatField(default=0.0, verbose_name='Blood loss in ml')),
                ('transfusion', models.BooleanField(default=False)),
                ('conversion_to_lap_open', models.BooleanField(default=False, verbose_name='Converted to Lap./Open surgery')),
                ('instruments_used', models.TextField(verbose_name='Instruments used')),
                ('adverse_events', models.TextField(verbose_name='Adverse events during surgery')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='optrix.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Postoperative',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('robotic_or_cleaning', models.BooleanField(default=False, verbose_name='Robotic OR cleaning')),
                ('returned_to_or', models.BooleanField(default=False, verbose_name='Returned to OR before discharge')),
                ('expected_discharge_date', models.DateField(verbose_name='Expected date of discharge')),
                ('actual_discharge_date', models.DateField(verbose_name='Actual date of discharge')),
                ('return_to_hospital', models.BooleanField(verbose_name='Readmitted to Hospital withing 30 days')),
                ('death_90', models.BooleanField(default=False, verbose_name='Death within 90 days')),
                ('complications', models.TextField(verbose_name='Complications description')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optrix.Surgery')),
            ],
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('materials_cost', models.FloatField(verbose_name='Cost of materials (consumables and instruments)')),
                ('medication_cost', models.FloatField(verbose_name='Cost of medication')),
                ('surgical_team', models.FloatField(verbose_name='Cost of surgical team')),
                ('other_costs', models.FloatField(verbose_name='Other personnel costs (nurses, etc.)')),
                ('or_time_cost', models.FloatField(verbose_name='Operating Room time cost')),
                ('icu_cost', models.FloatField(verbose_name='ICU cost')),
                ('robotic_cost', models.FloatField(verbose_name='Robotic system cost')),
                ('robot_maint_cost', models.FloatField(verbose_name='Robot maintenance fee')),
                ('sterilization_cost', models.FloatField(verbose_name='Sterilization cost')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optrix.Surgery')),
            ],
        ),
    ]
