# Generated by Django 3.0.3 on 2020-02-13 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optrix', '0003_auto_20200213_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='date',
            field=models.DateField(default=datetime.date(2020, 2, 13), verbose_name='Date of Surgery'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(default=datetime.date(2020, 2, 13), verbose_name='Date of admission'),
        ),
    ]
