# Generated by Django 3.0.3 on 2020-02-13 12:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('optrix', '0004_auto_20200213_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 13, 12, 44, 56, 129686, tzinfo=utc), verbose_name='Date of admission'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 13, 12, 44, 56, 130212, tzinfo=utc), verbose_name='Date of Surgery'),
        ),
    ]
