# Generated by Django 3.0.3 on 2020-03-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optrix', '0006_auto_20200226_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(verbose_name='Date of admission'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='date',
            field=models.DateField(verbose_name='Date of Surgery'),
        ),
    ]
