#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE ROLE optrixadmin;
    ALTER ROLE optrixadmin WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS PASSWORD NULL VALID UNTIL 'infinity';
    CREATE DATABASE optrix WITH OWNER optrixadmin ENCODING 'utf-8';
EOSQL